sudo: false
language: scala
jdk:
- openjdk8
before_install:
- export CXX='g++-4.8'
- nvm install 10.15.3 && nvm use 10.15.3 && npm install -g npm && npm install
- npm install svgexport -g
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.sbt/launchers"
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
- sbt textLintAll textTestAll textBuildHtml test &&
  wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/614d94496efdcf960871429e1c090c56d2018f68/setup/linux-installer.py
  | python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n');
  exec(sys.stdin.read()); main('~/calibre-bin', True)" >/dev/null &&
  export PATH="~/calibre-bin/calibre/:/home/travis/calibre-bin/calibre/:$PATH" &&
  sbt "textBuildEpub"
- git diff --exit-code
after_success:
- "./deploy.sh"
after_script:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
env:
  global:
  - secure: trVQXloshoD6qC8trtLviRLweSWOCJjq2TRHWuBcJqSJE8x7fJBcWnT2bex++gEPUQV2ee6cdF3/l/WcbPa+yaMDBvC3d4W/1WNXs8VxgI/M8UY5SfvB/nRnFGzxbGBW+AboHvvcvpDRk6jeTr+wQoRAKOIFOX6b3rcQfZh03RFIda9vOcCk48k1SpZKvcI9LHhB2ZA6pMeqk+KkaX8TKScVaOpoHJbnQT/uaMvPb0ZmdV2EKwOg6ZJffy3XPjwazWZWIg6mtPZwbHzVZGLSTnK8vlSqHwmBF49q9+3KjXe/DmBBMnTED+J8TNOv4eUSpmNlxQvBZVUgAVTQpIyQPdFmi6xzSWzS1AzW+ZUVMjTlyBUOzlAdOnqwtihtrvOLc3sGS8otMIBiuM49DWYCICYe/em0IFzsC6zK9okkoOC3Vw9U6Lgs/NvOlCwxpA0GFYpAGlfieqdfYnLVZDk8m0gSF37FcGxHQuRQlOk5f8c/JwvbU+FHBt5OFvGi3VeQ6mqOwPpYWz5Mz30tuKOXgH5RxDv5CLceSd0IsD5oHQEkFkP8m1woq6fUMCIlcv75w/1VVnMHTiTL9UqVnIvXCeEQFRpEZf/BWLe/C4QwrqowRGioZURemEnX4tzq0r9bYvPwIFw7akmDklSxzC2C/9vnpzRDtXJB33b/iGeTzeE=
  - secure: wjFFVfiveyqnv78CT4cNAv0/nJ41motXsc3ACFFISwZzgPhPrnPBIlKzllNeU/0HdWFTzp2qaKmUJtVIBtddsO4bcgbSRmrN395mRuGc/VTOHxA0sNROFAX/gbvE87v0ROZAHRVwgVblf3+3ENRbUxKVw9kxvuNMDB1cE4Yy0KN+nN76k4iHt/DlHkRoYu2iUvS8Ocx5AN1UJYi61Nc6WI19L2E44yc3yrZXNM4k2ISyxMYxPljjsdjZr0lY41hmHAcnWwHfA6+UhHrXP+5ZthESIrBSIINEV9+cXLszlawuxWI/Ip+/pzEbkg0QXQbRkLpvtc2lEwQIEgraIDeUyugzYItMINowyP2AmnHWl5xpIuYWqq1bvUIXwRMgIY+jofA31K2KzPqwAeuil5PPdkmd2cw9VuYsS3HAqN7L2TCjeLWD0k5HEmyj7gzWKgwyg7BZBtvQvlvUBJKdwfAVsYsPg/XNXVOekuX6hSaoS3KwZiwvsLHOVPiKeS3a05lOpWwCTyevOnCJKnr7Ln+/gRCdYXcpU/144RA5mNB8c5E1kfMOisiJwGl4dgauaufg4vtuYNaDwe2Ann1XwWR+hiiQufZDONFuyzNMEFKxKNFqwou5UPlYwkx0US42XDJaWOGYClL9Im/rQTjTknk1KPEALlMa8+/C2KReqqcCZG0=
  - secure: Ko278CFl8Iwe/DdN0kvrZknR2nOr8CKC3qwPJs7HuwOrHF7OIrHN9ry2OlA0efRLhss2Ip0O4/ZAPcTrJWOppSvcHD99zhAmnoMqd/x/BU2XD0Bb8aYKjbeGGlqtW3+idMbaFw14ozfgayG/+Nqmpws13GvLmlbFhhzv8U0N0FHQAUYr7zL1X+m2rBPLTuCHwNZZliTQVTxhVMFVDKVe97W8obJ/vRDeR92esRs1EchmqxbHuPh/x+1Jy67FAOzZruGBPs7LNnT2Wl7RiXCQR67smtwXiGTnvNLb201qP/DX6PNkxe9YeT7yTz9+q232zdkTKdAeM0EwG6kegV3RsGnDYVxvw3lQse7L1CnNuLcf+DfdyY4c/E8CciUgONAtsC4H7J6P9g/R03q6+pU8563P1v3qg1+rIK/CMcdvDIx0Sb/XDo39LhobMTzg2Z0PrRHHnk0vly4p6SdqVGHHec303/dIGpZHXMvo0A6D9dPBKgCxA/vmsLy6Udn4R32onzbUbTqYEZzDyfeb0zbff0IZf8AQ9+yFMrbIXZXzgfAILhMSue5FNqmE1xQK5ytFZ9W0vwhwdqw6HSrd9p6Gxs+lqU25I0Q6oVer+emWLUSIVFRz09ZUAJAeihBL/NYagiEsWhSGQTsfSPfk++dwUWcjQCV7Pzd0hiWSxV9dm0Q=
notifications:
  slack:
    secure: bAx/wydlY/47lCu72ebmWFohDqY3Xq7dKyRK4pwd5Hqkxic/kPbM+znhNUdMS5IaaCfx8CkVYCG++DRzPaSmAXki8FbDac1SivsMTyMYqcV+YtLhVFKm2Mth4aCgDIDzWx2GQTvv4JVBvhEGpqbveitTMsV4ojzicQZy+VqUTQqdRGaGDD6M4SNpxJ0gV4qxGbunnXqqmbIz+eOfm4fwtbH7GFUyPMV1XiRnckxVzildDz14b9K99PzdG+NKa+0Tx3OW/SJ1TDYc+O8Z4X9Ut1CqW31k3NpdtIOSt4uFgiUwFhkxm34uEhi4nS5xRRdad4xqSfL3WtgXDaBynxt7qjSjFxue38byR1/3qBfR27vIfr/go1X75PFwwCq05LbQLCDBWiXXVKJ0P7xWHx/TYzdXRUvlF9/vmejmLk/NkDLOkrqANod19+cBVlzOWtLessX8XZZmB3bzIWHFs1l9mZl8rrIuA3LRv+6ZXZoX2VA6Iesh4UajRSV+z3mRYvTjDX6sEAjmzN2bb1VxJw2u1nz0jOapeXvROfycrPoflyYk/VKWI9kZbJK0bHX7ilXjRq+baOBRNlYBwVcbthXqpu1n0VBcQQCUgZ7/MjOyp3/0yQBWiJ5w7WKLtbaIHoy2ub7oqiONZkR7YxYw8fUqGDy5qZSGs5DpUJl3x+25LIo=
